# Generated by Django 5.2.12 on 2026-08-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maidprofile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='maid_qr/'),
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
