# Generated by Django 5.2.12 on 2026-08-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_maidprofile_qr_code_maidprofile_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='maidprofile',
            name='current_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='current_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
